### ISSUE TITLE
0.9.0 source release does not build

### ISSUE THREAD

**Issue by lhhunghimself** [COMBINE-lab/piscem#25]
I tried downloading the release 0.9.0 source tarball and it does not compile (missing CMakeLists.txt in piscem/piscem-cpp)

It builds fine from the github when cloned recursively, but I get the exact same error when I don't clone recursively so I suspect that may be the problem with the tarball.

**Comment by rob-p** [comment]
Hi @lhhunghimself,

  Yes; this is a known issue. Somewhat embarrassingly, I don’t know how to get the automated build system here that produces the release tarballs (cargo-dist) to put the recursively cloned repo in the tarball.

If you have any idea how to do this, please let me know or feel free to submit a PR! If we were able to do this, the bioconda build would also become a *lot* easier, because we’d be able to move to a normal tagged release build rather than the source VCS build we currently have to use.

Thanks!
Rib

**Comment by rob-p** [comment]
Hi @lhhunghimself,

  Can you please try the [source_recursive.tar.gz](https://github.com/COMBINE-lab/piscem/releases/download/v0.10.0/source_recursive.tar.gz) in the v0.10.0 release.  It turns out the v0.9.0 release was mis-tagged, but v0.10.0 is correct.  I also figured out how to recursively include the submodules in the tarball (but not for the plain `source.tar.gz` releases, which is why this other artifact has a strange name).

  Please let me know if this works.

Thanks,
Rob

**Comment by lhhunghimself** [comment]
Works great thanks!

One other issue that I found however is really a problem with gcc 13. You need to include <cstdint> to use the advanced integer types like uint32_t. This causes both piscem and salmon to break when using gcc 13 to compile. Complies fine on gcc 12.  

In piscem only the KMC package is affected - so you would need to change the kmc_v3.2.2.patch by adding these lines

```
--- a/kmc_core/kff_writer.h
+++ b/kmc_core/kff_writer.h
@@ -1,5 +1,5 @@
 #pragma once
-
+#include <cstdint>
 #include <string>
 #include <vector>
```

For salmon you need to add the include to SalmonConfig.hpp  SalmonExceptions.hpp EffectiveLengthStats.hpp

Not a big deal - most people aren't using gcc 13 yet - I only found it when updating some Docker builds.

Thanks again for addressing the source file issue so quickly.

Hong

**Comment by rob-p** [comment]
Thanks for the report!  I'll adjust the KMC patch for the next release :).
